baseURL = 'https://fv-pfeffermaeuse.github.io/'
languageCode = 'de-DE'
title = 'Förderverein Kneipp-Kita Pfeffermäuse e.V.'
theme = 'blowfish'
defaultContentLanguage = "de"

enableRobotsTXT = true
paginate = 100
summaryLength = 30

# googleAnalytics = ""

[imaging]
  anchor = 'Center'

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  colorScheme = "forest" 
  defaultAppearance = "light"
  autoSwitchAppearance = "false"
  logo = "img/logo-small.jpg"
  description = "Der ehrenamtliche Förderverein Pfeffermäuse unterstützt die Kneipp-Kita Pfeffermäuse und verwirklicht tolle neue Projekte für die Kinder!"

[params.homepage]
  layout = "hero"
  showRecent = "true"
  cardView = "true"
  cardViewScreenWidth = "false"

[[menus.main]]
  name = "Über uns"
  pageRef = "about"
  weight = 10  